### ISSUE TITLE
powershell.exe -File ".\ParseNPSLogs.ps1"

### ISSUE THREAD

**Issue by usenetj23** [Xorlent/Microsoft-NPS-to-Syslog#1]
This two lines should be 
powershell.exe -File ".\NPS-Syslog.ps1"

??

**Comment by Xorlent** [comment]
I did change filenames early on in the project.  Could you please tell me where you found the reference to the old file name?  I'm unable to locate it.

**Comment by Xorlent** [comment]
The GitHub indexer finally started working again.  This has been fixed and thank you!
